# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.common import common_pb2 as common__pb2
from proto.vk_products_updater import vk_products_updater_pb2 as vk__products__updater__pb2


class VkProductsUpdaterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateProducts = channel.unary_unary(
                '/vk_products_getter.VkProductsUpdater/UpdateProducts',
                request_serializer=vk__products__updater__pb2.UpdateProductsRequest.SerializeToString,
                response_deserializer=common__pb2.EmptyResponse.FromString,
                )


class VkProductsUpdaterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VkProductsUpdaterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProducts,
                    request_deserializer=vk__products__updater__pb2.UpdateProductsRequest.FromString,
                    response_serializer=common__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vk_products_getter.VkProductsUpdater', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VkProductsUpdater(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vk_products_getter.VkProductsUpdater/UpdateProducts',
            vk__products__updater__pb2.UpdateProductsRequest.SerializeToString,
            common__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
