# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vk_products_updater.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.common import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vk_products_updater.proto',
  package='vk_products_getter',
  syntax='proto3',
  serialized_options=b'Z<github.com/nikhovas/diploma/go/lib/proto/vk_products_updater',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19vk_products_updater.proto\x12\x12vk_products_getter\x1a\x0c\x63ommon.proto\"\x7f\n\x15UpdateProductsRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x13\n\x0bvk_group_id\x18\x02 \x01(\x03\x12\x17\n\x0fis_user_request\x18\x03 \x01(\x08\x12\x19\n\x0cworker_token\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_worker_token2i\n\x11VkProductsUpdater\x12T\n\x0eUpdateProducts\x12).vk_products_getter.UpdateProductsRequest\x1a\x15.common.EmptyResponse\"\x00\x42>Z<github.com/nikhovas/diploma/go/lib/proto/vk_products_updaterb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_UPDATEPRODUCTSREQUEST = _descriptor.Descriptor(
  name='UpdateProductsRequest',
  full_name='vk_products_getter.UpdateProductsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='vk_products_getter.UpdateProductsRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vk_group_id', full_name='vk_products_getter.UpdateProductsRequest.vk_group_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_user_request', full_name='vk_products_getter.UpdateProductsRequest.is_user_request', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='worker_token', full_name='vk_products_getter.UpdateProductsRequest.worker_token', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_worker_token', full_name='vk_products_getter.UpdateProductsRequest._worker_token',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=63,
  serialized_end=190,
)

_UPDATEPRODUCTSREQUEST.oneofs_by_name['_worker_token'].fields.append(
  _UPDATEPRODUCTSREQUEST.fields_by_name['worker_token'])
_UPDATEPRODUCTSREQUEST.fields_by_name['worker_token'].containing_oneof = _UPDATEPRODUCTSREQUEST.oneofs_by_name['_worker_token']
DESCRIPTOR.message_types_by_name['UpdateProductsRequest'] = _UPDATEPRODUCTSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateProductsRequest = _reflection.GeneratedProtocolMessageType('UpdateProductsRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPRODUCTSREQUEST,
  '__module__' : 'vk_products_updater_pb2'
  # @@protoc_insertion_point(class_scope:vk_products_getter.UpdateProductsRequest)
  })
_sym_db.RegisterMessage(UpdateProductsRequest)


DESCRIPTOR._options = None

_VKPRODUCTSUPDATER = _descriptor.ServiceDescriptor(
  name='VkProductsUpdater',
  full_name='vk_products_getter.VkProductsUpdater',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=192,
  serialized_end=297,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateProducts',
    full_name='vk_products_getter.VkProductsUpdater.UpdateProducts',
    index=0,
    containing_service=None,
    input_type=_UPDATEPRODUCTSREQUEST,
    output_type=common__pb2._EMPTYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VKPRODUCTSUPDATER)

DESCRIPTOR.services_by_name['VkProductsUpdater'] = _VKPRODUCTSUPDATER

# @@protoc_insertion_point(module_scope)
