// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: consumer_messages.proto

package consumer_messages

import (
	common "github.com/nikhovas/diploma/go/lib/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplyBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplyMessageId       uint64 `protobuf:"varint,1,opt,name=replyMessageId,proto3" json:"replyMessageId,omitempty"`
	ReplyUnsupportedText string `protobuf:"bytes,2,opt,name=replyUnsupportedText,proto3" json:"replyUnsupportedText,omitempty"`
}

func (x *ReplyBlock) Reset() {
	*x = ReplyBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consumer_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyBlock) ProtoMessage() {}

func (x *ReplyBlock) ProtoReflect() protoreflect.Message {
	mi := &file_consumer_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyBlock.ProtoReflect.Descriptor instead.
func (*ReplyBlock) Descriptor() ([]byte, []int) {
	return file_consumer_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ReplyBlock) GetReplyMessageId() uint64 {
	if x != nil {
		return x.ReplyMessageId
	}
	return 0
}

func (x *ReplyBlock) GetReplyUnsupportedText() string {
	if x != nil {
		return x.ReplyUnsupportedText
	}
	return ""
}

type MessageToConsumer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid        string              `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MsgLocation *common.MsgLocation `protobuf:"bytes,2,opt,name=msgLocation,proto3" json:"msgLocation,omitempty"`
	Text        string              `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Reply       *ReplyBlock         `protobuf:"bytes,4,opt,name=reply,proto3,oneof" json:"reply,omitempty"`
}

func (x *MessageToConsumer) Reset() {
	*x = MessageToConsumer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consumer_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageToConsumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageToConsumer) ProtoMessage() {}

func (x *MessageToConsumer) ProtoReflect() protoreflect.Message {
	mi := &file_consumer_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageToConsumer.ProtoReflect.Descriptor instead.
func (*MessageToConsumer) Descriptor() ([]byte, []int) {
	return file_consumer_messages_proto_rawDescGZIP(), []int{1}
}

func (x *MessageToConsumer) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MessageToConsumer) GetMsgLocation() *common.MsgLocation {
	if x != nil {
		return x.MsgLocation
	}
	return nil
}

func (x *MessageToConsumer) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageToConsumer) GetReply() *ReplyBlock {
	if x != nil {
		return x.Reply
	}
	return nil
}

var File_consumer_messages_proto protoreflect.FileDescriptor

var file_consumer_messages_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x0a, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0e, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x32, 0x0a, 0x14, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x55, 0x6e, 0x73, 0x75, 0x70, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x55, 0x6e, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x54, 0x65, 0x78, 0x74, 0x22, 0xb6, 0x01, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x6f, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x35,
	0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x73, 0x67,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6d, 0x73, 0x67, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x38, 0x0a, 0x05, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3c, 0x5a,
	0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6b, 0x68,
	0x6f, 0x76, 0x61, 0x73, 0x2f, 0x64, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x2f, 0x67, 0x6f, 0x2f,
	0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_consumer_messages_proto_rawDescOnce sync.Once
	file_consumer_messages_proto_rawDescData = file_consumer_messages_proto_rawDesc
)

func file_consumer_messages_proto_rawDescGZIP() []byte {
	file_consumer_messages_proto_rawDescOnce.Do(func() {
		file_consumer_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_consumer_messages_proto_rawDescData)
	})
	return file_consumer_messages_proto_rawDescData
}

var file_consumer_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_consumer_messages_proto_goTypes = []interface{}{
	(*ReplyBlock)(nil),         // 0: consumer_messages.ReplyBlock
	(*MessageToConsumer)(nil),  // 1: consumer_messages.MessageToConsumer
	(*common.MsgLocation)(nil), // 2: common.MsgLocation
}
var file_consumer_messages_proto_depIdxs = []int32{
	2, // 0: consumer_messages.MessageToConsumer.msgLocation:type_name -> common.MsgLocation
	0, // 1: consumer_messages.MessageToConsumer.reply:type_name -> consumer_messages.ReplyBlock
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_consumer_messages_proto_init() }
func file_consumer_messages_proto_init() {
	if File_consumer_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_consumer_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consumer_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageToConsumer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_consumer_messages_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consumer_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consumer_messages_proto_goTypes,
		DependencyIndexes: file_consumer_messages_proto_depIdxs,
		MessageInfos:      file_consumer_messages_proto_msgTypes,
	}.Build()
	File_consumer_messages_proto = out.File
	file_consumer_messages_proto_rawDesc = nil
	file_consumer_messages_proto_goTypes = nil
	file_consumer_messages_proto_depIdxs = nil
}
