// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: TelegramStaffBot.proto

package TelegramStaffBot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewQuestionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId  int64  `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Question string `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
}

func (x *NewQuestionRequest) Reset() {
	*x = NewQuestionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TelegramStaffBot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewQuestionRequest) ProtoMessage() {}

func (x *NewQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TelegramStaffBot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewQuestionRequest.ProtoReflect.Descriptor instead.
func (*NewQuestionRequest) Descriptor() ([]byte, []int) {
	return file_TelegramStaffBot_proto_rawDescGZIP(), []int{0}
}

func (x *NewQuestionRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *NewQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type NotifyBotStatusChangeTelegramRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64 `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Enabled bool  `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *NotifyBotStatusChangeTelegramRequest) Reset() {
	*x = NotifyBotStatusChangeTelegramRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TelegramStaffBot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyBotStatusChangeTelegramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBotStatusChangeTelegramRequest) ProtoMessage() {}

func (x *NotifyBotStatusChangeTelegramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TelegramStaffBot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBotStatusChangeTelegramRequest.ProtoReflect.Descriptor instead.
func (*NotifyBotStatusChangeTelegramRequest) Descriptor() ([]byte, []int) {
	return file_TelegramStaffBot_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyBotStatusChangeTelegramRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *NotifyBotStatusChangeTelegramRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TelegramStaffBot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TelegramStaffBot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_TelegramStaffBot_proto_rawDescGZIP(), []int{2}
}

var File_TelegramStaffBot_proto protoreflect.FileDescriptor

var file_TelegramStaffBot_proto_rawDesc = []byte{
	0x0a, 0x16, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x66, 0x66, 0x42,
	0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x12, 0x4e, 0x65, 0x77, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5a, 0x0a, 0x24, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x42, 0x6f,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x65, 0x6c,
	0x65, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xa6, 0x01, 0x0a, 0x10, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x42, 0x6f, 0x74, 0x12, 0x38, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x65,
	0x77, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e, 0x4e, 0x65, 0x77, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x58, 0x0a, 0x1d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x42, 0x6f, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x25, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x42, 0x6f, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6b, 0x68, 0x6f, 0x76, 0x61,
	0x73, 0x2f, 0x64, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x42, 0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TelegramStaffBot_proto_rawDescOnce sync.Once
	file_TelegramStaffBot_proto_rawDescData = file_TelegramStaffBot_proto_rawDesc
)

func file_TelegramStaffBot_proto_rawDescGZIP() []byte {
	file_TelegramStaffBot_proto_rawDescOnce.Do(func() {
		file_TelegramStaffBot_proto_rawDescData = protoimpl.X.CompressGZIP(file_TelegramStaffBot_proto_rawDescData)
	})
	return file_TelegramStaffBot_proto_rawDescData
}

var file_TelegramStaffBot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_TelegramStaffBot_proto_goTypes = []interface{}{
	(*NewQuestionRequest)(nil),                   // 0: NewQuestionRequest
	(*NotifyBotStatusChangeTelegramRequest)(nil), // 1: NotifyBotStatusChangeTelegramRequest
	(*EmptyResponse)(nil),                        // 2: EmptyResponse
}
var file_TelegramStaffBot_proto_depIdxs = []int32{
	0, // 0: TelegramStaffBot.SendNewQuestion:input_type -> NewQuestionRequest
	1, // 1: TelegramStaffBot.NotifyBotStatusTelegramChange:input_type -> NotifyBotStatusChangeTelegramRequest
	2, // 2: TelegramStaffBot.SendNewQuestion:output_type -> EmptyResponse
	2, // 3: TelegramStaffBot.NotifyBotStatusTelegramChange:output_type -> EmptyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TelegramStaffBot_proto_init() }
func file_TelegramStaffBot_proto_init() {
	if File_TelegramStaffBot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TelegramStaffBot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewQuestionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TelegramStaffBot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyBotStatusChangeTelegramRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TelegramStaffBot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TelegramStaffBot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TelegramStaffBot_proto_goTypes,
		DependencyIndexes: file_TelegramStaffBot_proto_depIdxs,
		MessageInfos:      file_TelegramStaffBot_proto_msgTypes,
	}.Build()
	File_TelegramStaffBot_proto = out.File
	file_TelegramStaffBot_proto_rawDesc = nil
	file_TelegramStaffBot_proto_goTypes = nil
	file_TelegramStaffBot_proto_depIdxs = nil
}
