// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: Control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelegramMessageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId        int64   `protobuf:"varint,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	IsChatPrivate bool    `protobuf:"varint,2,opt,name=isChatPrivate,proto3" json:"isChatPrivate,omitempty"`
	UserId        int64   `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	BotName       *string `protobuf:"bytes,4,opt,name=botName,proto3,oneof" json:"botName,omitempty"`
}

func (x *TelegramMessageInfo) Reset() {
	*x = TelegramMessageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelegramMessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramMessageInfo) ProtoMessage() {}

func (x *TelegramMessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramMessageInfo.ProtoReflect.Descriptor instead.
func (*TelegramMessageInfo) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{0}
}

func (x *TelegramMessageInfo) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *TelegramMessageInfo) GetIsChatPrivate() bool {
	if x != nil {
		return x.IsChatPrivate
	}
	return false
}

func (x *TelegramMessageInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TelegramMessageInfo) GetBotName() string {
	if x != nil && x.BotName != nil {
		return *x.BotName
	}
	return ""
}

type MessageInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Info:
	//	*MessageInformation_Telegram
	Info isMessageInformation_Info `protobuf_oneof:"info"`
}

func (x *MessageInformation) Reset() {
	*x = MessageInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInformation) ProtoMessage() {}

func (x *MessageInformation) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInformation.ProtoReflect.Descriptor instead.
func (*MessageInformation) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{1}
}

func (m *MessageInformation) GetInfo() isMessageInformation_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (x *MessageInformation) GetTelegram() *TelegramMessageInfo {
	if x, ok := x.GetInfo().(*MessageInformation_Telegram); ok {
		return x.Telegram
	}
	return nil
}

type isMessageInformation_Info interface {
	isMessageInformation_Info()
}

type MessageInformation_Telegram struct {
	Telegram *TelegramMessageInfo `protobuf:"bytes,1,opt,name=telegram,proto3,oneof"`
}

func (*MessageInformation_Telegram) isMessageInformation_Info() {}

type CommonBotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Token   string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	GroupId int64  `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *CommonBotInfo) Reset() {
	*x = CommonBotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonBotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonBotInfo) ProtoMessage() {}

func (x *CommonBotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonBotInfo.ProtoReflect.Descriptor instead.
func (*CommonBotInfo) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{2}
}

func (x *CommonBotInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommonBotInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CommonBotInfo) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type OptionalCommonBotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Token   *string `protobuf:"bytes,2,opt,name=token,proto3,oneof" json:"token,omitempty"`
	GroupId *int64  `protobuf:"varint,3,opt,name=groupId,proto3,oneof" json:"groupId,omitempty"`
}

func (x *OptionalCommonBotInfo) Reset() {
	*x = OptionalCommonBotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalCommonBotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalCommonBotInfo) ProtoMessage() {}

func (x *OptionalCommonBotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalCommonBotInfo.ProtoReflect.Descriptor instead.
func (*OptionalCommonBotInfo) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{3}
}

func (x *OptionalCommonBotInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *OptionalCommonBotInfo) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *OptionalCommonBotInfo) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

type TelegramBotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId int64 `protobuf:"varint,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
}

func (x *TelegramBotInfo) Reset() {
	*x = TelegramBotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelegramBotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramBotInfo) ProtoMessage() {}

func (x *TelegramBotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramBotInfo.ProtoReflect.Descriptor instead.
func (*TelegramBotInfo) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{4}
}

func (x *TelegramBotInfo) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type OptionalTelegramBotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId *int64 `protobuf:"varint,1,opt,name=chatId,proto3,oneof" json:"chatId,omitempty"`
}

func (x *OptionalTelegramBotInfo) Reset() {
	*x = OptionalTelegramBotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalTelegramBotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalTelegramBotInfo) ProtoMessage() {}

func (x *OptionalTelegramBotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalTelegramBotInfo.ProtoReflect.Descriptor instead.
func (*OptionalTelegramBotInfo) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{5}
}

func (x *OptionalTelegramBotInfo) GetChatId() int64 {
	if x != nil && x.ChatId != nil {
		return *x.ChatId
	}
	return 0
}

type PlatformBotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Platform:
	//	*PlatformBotInfo_Telegram
	Platform isPlatformBotInfo_Platform `protobuf_oneof:"platform"`
}

func (x *PlatformBotInfo) Reset() {
	*x = PlatformBotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatformBotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformBotInfo) ProtoMessage() {}

func (x *PlatformBotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformBotInfo.ProtoReflect.Descriptor instead.
func (*PlatformBotInfo) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{6}
}

func (m *PlatformBotInfo) GetPlatform() isPlatformBotInfo_Platform {
	if m != nil {
		return m.Platform
	}
	return nil
}

func (x *PlatformBotInfo) GetTelegram() *TelegramBotInfo {
	if x, ok := x.GetPlatform().(*PlatformBotInfo_Telegram); ok {
		return x.Telegram
	}
	return nil
}

type isPlatformBotInfo_Platform interface {
	isPlatformBotInfo_Platform()
}

type PlatformBotInfo_Telegram struct {
	Telegram *TelegramBotInfo `protobuf:"bytes,1,opt,name=telegram,proto3,oneof"`
}

func (*PlatformBotInfo_Telegram) isPlatformBotInfo_Platform() {}

type OptionalPlatformBotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Platform:
	//	*OptionalPlatformBotInfo_Telegram
	Platform isOptionalPlatformBotInfo_Platform `protobuf_oneof:"platform"`
}

func (x *OptionalPlatformBotInfo) Reset() {
	*x = OptionalPlatformBotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalPlatformBotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalPlatformBotInfo) ProtoMessage() {}

func (x *OptionalPlatformBotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalPlatformBotInfo.ProtoReflect.Descriptor instead.
func (*OptionalPlatformBotInfo) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{7}
}

func (m *OptionalPlatformBotInfo) GetPlatform() isOptionalPlatformBotInfo_Platform {
	if m != nil {
		return m.Platform
	}
	return nil
}

func (x *OptionalPlatformBotInfo) GetTelegram() *OptionalTelegramBotInfo {
	if x, ok := x.GetPlatform().(*OptionalPlatformBotInfo_Telegram); ok {
		return x.Telegram
	}
	return nil
}

type isOptionalPlatformBotInfo_Platform interface {
	isOptionalPlatformBotInfo_Platform()
}

type OptionalPlatformBotInfo_Telegram struct {
	Telegram *OptionalTelegramBotInfo `protobuf:"bytes,1,opt,name=telegram,proto3,oneof"`
}

func (*OptionalPlatformBotInfo_Telegram) isOptionalPlatformBotInfo_Platform() {}

type BotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonBotInfo   *CommonBotInfo   `protobuf:"bytes,1,opt,name=commonBotInfo,proto3" json:"commonBotInfo,omitempty"`
	PlatformBotInfo *PlatformBotInfo `protobuf:"bytes,2,opt,name=platformBotInfo,proto3" json:"platformBotInfo,omitempty"`
}

func (x *BotInfo) Reset() {
	*x = BotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotInfo) ProtoMessage() {}

func (x *BotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotInfo.ProtoReflect.Descriptor instead.
func (*BotInfo) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{8}
}

func (x *BotInfo) GetCommonBotInfo() *CommonBotInfo {
	if x != nil {
		return x.CommonBotInfo
	}
	return nil
}

func (x *BotInfo) GetPlatformBotInfo() *PlatformBotInfo {
	if x != nil {
		return x.PlatformBotInfo
	}
	return nil
}

type OptionalBotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonBotInfo   *OptionalCommonBotInfo   `protobuf:"bytes,1,opt,name=commonBotInfo,proto3,oneof" json:"commonBotInfo,omitempty"`
	PlatformBotInfo *OptionalPlatformBotInfo `protobuf:"bytes,2,opt,name=platformBotInfo,proto3,oneof" json:"platformBotInfo,omitempty"`
}

func (x *OptionalBotInfo) Reset() {
	*x = OptionalBotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalBotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalBotInfo) ProtoMessage() {}

func (x *OptionalBotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalBotInfo.ProtoReflect.Descriptor instead.
func (*OptionalBotInfo) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{9}
}

func (x *OptionalBotInfo) GetCommonBotInfo() *OptionalCommonBotInfo {
	if x != nil {
		return x.CommonBotInfo
	}
	return nil
}

func (x *OptionalBotInfo) GetPlatformBotInfo() *OptionalPlatformBotInfo {
	if x != nil {
		return x.PlatformBotInfo
	}
	return nil
}

type CommonShopKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to CommonKey:
	//	*CommonShopKey_Id
	//	*CommonShopKey_Name
	//	*CommonShopKey_VkGroupId
	CommonKey isCommonShopKey_CommonKey `protobuf_oneof:"commonKey"`
}

func (x *CommonShopKey) Reset() {
	*x = CommonShopKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonShopKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonShopKey) ProtoMessage() {}

func (x *CommonShopKey) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonShopKey.ProtoReflect.Descriptor instead.
func (*CommonShopKey) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{10}
}

func (m *CommonShopKey) GetCommonKey() isCommonShopKey_CommonKey {
	if m != nil {
		return m.CommonKey
	}
	return nil
}

func (x *CommonShopKey) GetId() int64 {
	if x, ok := x.GetCommonKey().(*CommonShopKey_Id); ok {
		return x.Id
	}
	return 0
}

func (x *CommonShopKey) GetName() string {
	if x, ok := x.GetCommonKey().(*CommonShopKey_Name); ok {
		return x.Name
	}
	return ""
}

func (x *CommonShopKey) GetVkGroupId() int64 {
	if x, ok := x.GetCommonKey().(*CommonShopKey_VkGroupId); ok {
		return x.VkGroupId
	}
	return 0
}

type isCommonShopKey_CommonKey interface {
	isCommonShopKey_CommonKey()
}

type CommonShopKey_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type CommonShopKey_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

type CommonShopKey_VkGroupId struct {
	VkGroupId int64 `protobuf:"varint,3,opt,name=vkGroupId,proto3,oneof"`
}

func (*CommonShopKey_Id) isCommonShopKey_CommonKey() {}

func (*CommonShopKey_Name) isCommonShopKey_CommonKey() {}

func (*CommonShopKey_VkGroupId) isCommonShopKey_CommonKey() {}

type TelegramStaffShopKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to TelegramKey:
	//	*TelegramStaffShopKey_GroupId
	TelegramKey isTelegramStaffShopKey_TelegramKey `protobuf_oneof:"telegramKey"`
}

func (x *TelegramStaffShopKey) Reset() {
	*x = TelegramStaffShopKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelegramStaffShopKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramStaffShopKey) ProtoMessage() {}

func (x *TelegramStaffShopKey) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramStaffShopKey.ProtoReflect.Descriptor instead.
func (*TelegramStaffShopKey) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{11}
}

func (m *TelegramStaffShopKey) GetTelegramKey() isTelegramStaffShopKey_TelegramKey {
	if m != nil {
		return m.TelegramKey
	}
	return nil
}

func (x *TelegramStaffShopKey) GetGroupId() int64 {
	if x, ok := x.GetTelegramKey().(*TelegramStaffShopKey_GroupId); ok {
		return x.GroupId
	}
	return 0
}

type isTelegramStaffShopKey_TelegramKey interface {
	isTelegramStaffShopKey_TelegramKey()
}

type TelegramStaffShopKey_GroupId struct {
	GroupId int64 `protobuf:"varint,1,opt,name=groupId,proto3,oneof"`
}

func (*TelegramStaffShopKey_GroupId) isTelegramStaffShopKey_TelegramKey() {}

type ShopKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Key:
	//	*ShopKey_Common
	//	*ShopKey_TelegramStaff
	Key isShopKey_Key `protobuf_oneof:"key"`
}

func (x *ShopKey) Reset() {
	*x = ShopKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopKey) ProtoMessage() {}

func (x *ShopKey) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopKey.ProtoReflect.Descriptor instead.
func (*ShopKey) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{12}
}

func (m *ShopKey) GetKey() isShopKey_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (x *ShopKey) GetCommon() *CommonShopKey {
	if x, ok := x.GetKey().(*ShopKey_Common); ok {
		return x.Common
	}
	return nil
}

func (x *ShopKey) GetTelegramStaff() *TelegramStaffShopKey {
	if x, ok := x.GetKey().(*ShopKey_TelegramStaff); ok {
		return x.TelegramStaff
	}
	return nil
}

type isShopKey_Key interface {
	isShopKey_Key()
}

type ShopKey_Common struct {
	Common *CommonShopKey `protobuf:"bytes,1,opt,name=common,proto3,oneof"`
}

type ShopKey_TelegramStaff struct {
	TelegramStaff *TelegramStaffShopKey `protobuf:"bytes,2,opt,name=telegramStaff,proto3,oneof"`
}

func (*ShopKey_Common) isShopKey_Key() {}

func (*ShopKey_TelegramStaff) isShopKey_Key() {}

type EmptyOkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyOkResponse) Reset() {
	*x = EmptyOkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyOkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyOkResponse) ProtoMessage() {}

func (x *EmptyOkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyOkResponse.ProtoReflect.Descriptor instead.
func (*EmptyOkResponse) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{13}
}

type NoRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredOneOf []string `protobuf:"bytes,1,rep,name=requiredOneOf,proto3" json:"requiredOneOf,omitempty"`
}

func (x *NoRoleResponse) Reset() {
	*x = NoRoleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoRoleResponse) ProtoMessage() {}

func (x *NoRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoRoleResponse.ProtoReflect.Descriptor instead.
func (*NoRoleResponse) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{14}
}

func (x *NoRoleResponse) GetRequiredOneOf() []string {
	if x != nil {
		return x.RequiredOneOf
	}
	return nil
}

type BadChatType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShouldBePrivate bool `protobuf:"varint,1,opt,name=shouldBePrivate,proto3" json:"shouldBePrivate,omitempty"`
}

func (x *BadChatType) Reset() {
	*x = BadChatType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BadChatType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadChatType) ProtoMessage() {}

func (x *BadChatType) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadChatType.ProtoReflect.Descriptor instead.
func (*BadChatType) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{15}
}

func (x *BadChatType) GetShouldBePrivate() bool {
	if x != nil {
		return x.ShouldBePrivate
	}
	return false
}

type DefaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Resp:
	//	*DefaultResponse_Success
	//	*DefaultResponse_NoRoleError
	//	*DefaultResponse_BadChatType
	Resp isDefaultResponse_Resp `protobuf_oneof:"resp"`
}

func (x *DefaultResponse) Reset() {
	*x = DefaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultResponse) ProtoMessage() {}

func (x *DefaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultResponse.ProtoReflect.Descriptor instead.
func (*DefaultResponse) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{16}
}

func (m *DefaultResponse) GetResp() isDefaultResponse_Resp {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (x *DefaultResponse) GetSuccess() *EmptyOkResponse {
	if x, ok := x.GetResp().(*DefaultResponse_Success); ok {
		return x.Success
	}
	return nil
}

func (x *DefaultResponse) GetNoRoleError() *NoRoleResponse {
	if x, ok := x.GetResp().(*DefaultResponse_NoRoleError); ok {
		return x.NoRoleError
	}
	return nil
}

func (x *DefaultResponse) GetBadChatType() *BadChatType {
	if x, ok := x.GetResp().(*DefaultResponse_BadChatType); ok {
		return x.BadChatType
	}
	return nil
}

type isDefaultResponse_Resp interface {
	isDefaultResponse_Resp()
}

type DefaultResponse_Success struct {
	Success *EmptyOkResponse `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type DefaultResponse_NoRoleError struct {
	NoRoleError *NoRoleResponse `protobuf:"bytes,2,opt,name=noRoleError,proto3,oneof"`
}

type DefaultResponse_BadChatType struct {
	BadChatType *BadChatType `protobuf:"bytes,3,opt,name=badChatType,proto3,oneof"`
}

func (*DefaultResponse_Success) isDefaultResponse_Resp() {}

func (*DefaultResponse_NoRoleError) isDefaultResponse_Resp() {}

func (*DefaultResponse_BadChatType) isDefaultResponse_Resp() {}

type AddQuestionAnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageInfo        *MessageInformation `protobuf:"bytes,1,opt,name=messageInfo,proto3" json:"messageInfo,omitempty"`
	Key                *ShopKey            `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Question           string              `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answer             string              `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	CheckQuestionInSet bool                `protobuf:"varint,5,opt,name=checkQuestionInSet,proto3" json:"checkQuestionInSet,omitempty"`
}

func (x *AddQuestionAnswerRequest) Reset() {
	*x = AddQuestionAnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddQuestionAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionAnswerRequest) ProtoMessage() {}

func (x *AddQuestionAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionAnswerRequest.ProtoReflect.Descriptor instead.
func (*AddQuestionAnswerRequest) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{17}
}

func (x *AddQuestionAnswerRequest) GetMessageInfo() *MessageInformation {
	if x != nil {
		return x.MessageInfo
	}
	return nil
}

func (x *AddQuestionAnswerRequest) GetKey() *ShopKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AddQuestionAnswerRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AddQuestionAnswerRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AddQuestionAnswerRequest) GetCheckQuestionInSet() bool {
	if x != nil {
		return x.CheckQuestionInSet
	}
	return false
}

type ChangeBotStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageInfo *MessageInformation `protobuf:"bytes,1,opt,name=messageInfo,proto3" json:"messageInfo,omitempty"`
	Key         *ShopKey            `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ToEnabled   bool                `protobuf:"varint,3,opt,name=toEnabled,proto3" json:"toEnabled,omitempty"`
}

func (x *ChangeBotStateRequest) Reset() {
	*x = ChangeBotStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeBotStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBotStateRequest) ProtoMessage() {}

func (x *ChangeBotStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBotStateRequest.ProtoReflect.Descriptor instead.
func (*ChangeBotStateRequest) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{18}
}

func (x *ChangeBotStateRequest) GetMessageInfo() *MessageInformation {
	if x != nil {
		return x.MessageInfo
	}
	return nil
}

func (x *ChangeBotStateRequest) GetKey() *ShopKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ChangeBotStateRequest) GetToEnabled() bool {
	if x != nil {
		return x.ToEnabled
	}
	return false
}

type AddShopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageInfo *MessageInformation `protobuf:"bytes,1,opt,name=messageInfo,proto3" json:"messageInfo,omitempty"`
	Bot         *BotInfo            `protobuf:"bytes,2,opt,name=bot,proto3" json:"bot,omitempty"`
}

func (x *AddShopRequest) Reset() {
	*x = AddShopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShopRequest) ProtoMessage() {}

func (x *AddShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShopRequest.ProtoReflect.Descriptor instead.
func (*AddShopRequest) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{19}
}

func (x *AddShopRequest) GetMessageInfo() *MessageInformation {
	if x != nil {
		return x.MessageInfo
	}
	return nil
}

func (x *AddShopRequest) GetBot() *BotInfo {
	if x != nil {
		return x.Bot
	}
	return nil
}

type DeleteShopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageInfo *MessageInformation `protobuf:"bytes,1,opt,name=messageInfo,proto3" json:"messageInfo,omitempty"`
	Key         *ShopKey            `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteShopRequest) Reset() {
	*x = DeleteShopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShopRequest) ProtoMessage() {}

func (x *DeleteShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShopRequest.ProtoReflect.Descriptor instead.
func (*DeleteShopRequest) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteShopRequest) GetMessageInfo() *MessageInformation {
	if x != nil {
		return x.MessageInfo
	}
	return nil
}

func (x *DeleteShopRequest) GetKey() *ShopKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type ModifyShopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageInfo *MessageInformation `protobuf:"bytes,1,opt,name=messageInfo,proto3" json:"messageInfo,omitempty"`
	Key         *ShopKey            `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Bot         *OptionalBotInfo    `protobuf:"bytes,4,opt,name=bot,proto3" json:"bot,omitempty"`
}

func (x *ModifyShopRequest) Reset() {
	*x = ModifyShopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyShopRequest) ProtoMessage() {}

func (x *ModifyShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyShopRequest.ProtoReflect.Descriptor instead.
func (*ModifyShopRequest) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{21}
}

func (x *ModifyShopRequest) GetMessageInfo() *MessageInformation {
	if x != nil {
		return x.MessageInfo
	}
	return nil
}

func (x *ModifyShopRequest) GetKey() *ShopKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ModifyShopRequest) GetBot() *OptionalBotInfo {
	if x != nil {
		return x.Bot
	}
	return nil
}

type ListShopsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageInfo *MessageInformation `protobuf:"bytes,1,opt,name=messageInfo,proto3" json:"messageInfo,omitempty"`
}

func (x *ListShopsRequest) Reset() {
	*x = ListShopsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopsRequest) ProtoMessage() {}

func (x *ListShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopsRequest.ProtoReflect.Descriptor instead.
func (*ListShopsRequest) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{22}
}

func (x *ListShopsRequest) GetMessageInfo() *MessageInformation {
	if x != nil {
		return x.MessageInfo
	}
	return nil
}

type ListBotSuccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bots []*CommonBotInfo `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
}

func (x *ListBotSuccessResponse) Reset() {
	*x = ListBotSuccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBotSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBotSuccessResponse) ProtoMessage() {}

func (x *ListBotSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBotSuccessResponse.ProtoReflect.Descriptor instead.
func (*ListBotSuccessResponse) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{23}
}

func (x *ListBotSuccessResponse) GetBots() []*CommonBotInfo {
	if x != nil {
		return x.Bots
	}
	return nil
}

type ListShopsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Resp:
	//	*ListShopsResponse_Success
	//	*ListShopsResponse_NoRoleError
	//	*ListShopsResponse_BadChatType
	Resp isListShopsResponse_Resp `protobuf_oneof:"resp"`
}

func (x *ListShopsResponse) Reset() {
	*x = ListShopsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopsResponse) ProtoMessage() {}

func (x *ListShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopsResponse.ProtoReflect.Descriptor instead.
func (*ListShopsResponse) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{24}
}

func (m *ListShopsResponse) GetResp() isListShopsResponse_Resp {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (x *ListShopsResponse) GetSuccess() *ListBotSuccessResponse {
	if x, ok := x.GetResp().(*ListShopsResponse_Success); ok {
		return x.Success
	}
	return nil
}

func (x *ListShopsResponse) GetNoRoleError() *NoRoleResponse {
	if x, ok := x.GetResp().(*ListShopsResponse_NoRoleError); ok {
		return x.NoRoleError
	}
	return nil
}

func (x *ListShopsResponse) GetBadChatType() *BadChatType {
	if x, ok := x.GetResp().(*ListShopsResponse_BadChatType); ok {
		return x.BadChatType
	}
	return nil
}

type isListShopsResponse_Resp interface {
	isListShopsResponse_Resp()
}

type ListShopsResponse_Success struct {
	Success *ListBotSuccessResponse `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type ListShopsResponse_NoRoleError struct {
	NoRoleError *NoRoleResponse `protobuf:"bytes,2,opt,name=noRoleError,proto3,oneof"`
}

type ListShopsResponse_BadChatType struct {
	BadChatType *BadChatType `protobuf:"bytes,3,opt,name=badChatType,proto3,oneof"`
}

func (*ListShopsResponse_Success) isListShopsResponse_Resp() {}

func (*ListShopsResponse_NoRoleError) isListShopsResponse_Resp() {}

func (*ListShopsResponse_BadChatType) isListShopsResponse_Resp() {}

type ChangeUserRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageInfo  *MessageInformation `protobuf:"bytes,1,opt,name=messageInfo,proto3" json:"messageInfo,omitempty"`
	ModifyUserId int64               `protobuf:"varint,2,opt,name=modifyUserId,proto3" json:"modifyUserId,omitempty"`
	Role         string              `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	IsAddAction  bool                `protobuf:"varint,4,opt,name=isAddAction,proto3" json:"isAddAction,omitempty"`
}

func (x *ChangeUserRoleRequest) Reset() {
	*x = ChangeUserRoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserRoleRequest) ProtoMessage() {}

func (x *ChangeUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserRoleRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{25}
}

func (x *ChangeUserRoleRequest) GetMessageInfo() *MessageInformation {
	if x != nil {
		return x.MessageInfo
	}
	return nil
}

func (x *ChangeUserRoleRequest) GetModifyUserId() int64 {
	if x != nil {
		return x.ModifyUserId
	}
	return 0
}

func (x *ChangeUserRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChangeUserRoleRequest) GetIsAddAction() bool {
	if x != nil {
		return x.IsAddAction
	}
	return false
}

type AddQuestionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      *ShopKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Question string   `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
}

func (x *AddQuestionRequest) Reset() {
	*x = AddQuestionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionRequest) ProtoMessage() {}

func (x *AddQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionRequest.ProtoReflect.Descriptor instead.
func (*AddQuestionRequest) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{26}
}

func (x *AddQuestionRequest) GetKey() *ShopKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AddQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type NotifyBotStatusChangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       *ShopKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ToEnabled bool     `protobuf:"varint,2,opt,name=toEnabled,proto3" json:"toEnabled,omitempty"`
}

func (x *NotifyBotStatusChangeRequest) Reset() {
	*x = NotifyBotStatusChangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyBotStatusChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBotStatusChangeRequest) ProtoMessage() {}

func (x *NotifyBotStatusChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBotStatusChangeRequest.ProtoReflect.Descriptor instead.
func (*NotifyBotStatusChangeRequest) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{27}
}

func (x *NotifyBotStatusChangeRequest) GetKey() *ShopKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *NotifyBotStatusChangeRequest) GetToEnabled() bool {
	if x != nil {
		return x.ToEnabled
	}
	return false
}

type GetShopIdByKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId int64 `protobuf:"varint,1,opt,name=shopId,proto3" json:"shopId,omitempty"`
}

func (x *GetShopIdByKeyResponse) Reset() {
	*x = GetShopIdByKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Control_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopIdByKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopIdByKeyResponse) ProtoMessage() {}

func (x *GetShopIdByKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Control_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopIdByKeyResponse.ProtoReflect.Descriptor instead.
func (*GetShopIdByKeyResponse) Descriptor() ([]byte, []int) {
	return file_Control_proto_rawDescGZIP(), []int{28}
}

func (x *GetShopIdByKeyResponse) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

var File_Control_proto protoreflect.FileDescriptor

var file_Control_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x96, 0x01, 0x0a, 0x13, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x69, 0x73, 0x43, 0x68, 0x61, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x43, 0x68, 0x61, 0x74, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x07, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x07, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32,
	0x0a, 0x08, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72,
	0x61, 0x6d, 0x42, 0x06, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x53, 0x0a, 0x0d, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22,
	0x89, 0x01, 0x0a, 0x15, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x02,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x0f, 0x54,
	0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x17, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1b, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x0f, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a, 0x08,
	0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x48, 0x00, 0x52, 0x08, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x0a, 0x0a, 0x08,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x5d, 0x0a, 0x17, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x36, 0x0a, 0x08, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48,
	0x00, 0x52, 0x08, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x0a, 0x0a, 0x08, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x7b, 0x0a, 0x07, 0x42, 0x6f, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x34, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x42, 0x6f, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3a, 0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x42, 0x6f, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0xc3, 0x01, 0x0a, 0x0f, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x41, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x47, 0x0a, 0x0f, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x01,
	0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x42,
	0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x64, 0x0a, 0x0d, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x76, 0x6b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x09, 0x76, 0x6b, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4b, 0x65, 0x79,
	0x22, 0x41, 0x0a, 0x14, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x53, 0x68, 0x6f, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x42, 0x0d, 0x0a, 0x0b, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d,
	0x4b, 0x65, 0x79, 0x22, 0x79, 0x0a, 0x07, 0x53, 0x68, 0x6f, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x28,
	0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x70, 0x4b, 0x65, 0x79, 0x48, 0x00,
	0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x0d, 0x74, 0x65, 0x6c, 0x65,
	0x67, 0x72, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x66, 0x66, 0x53,
	0x68, 0x6f, 0x70, 0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x0d, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72,
	0x61, 0x6d, 0x53, 0x74, 0x61, 0x66, 0x66, 0x42, 0x05, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x11,
	0x0a, 0x0f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x36, 0x0a, 0x0e, 0x4e, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x4f,
	0x6e, 0x65, 0x4f, 0x66, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x22, 0x37, 0x0a, 0x0b, 0x42, 0x61, 0x64,
	0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x68, 0x6f, 0x75,
	0x6c, 0x64, 0x42, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x42, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x22, 0xae, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4f,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x33, 0x0a, 0x0b, 0x6e, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4e, 0x6f, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x6e, 0x6f,
	0x52, 0x6f, 0x6c, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x30, 0x0a, 0x0b, 0x62, 0x61, 0x64,
	0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x42, 0x61, 0x64, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0b,
	0x62, 0x61, 0x64, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x72,
	0x65, 0x73, 0x70, 0x22, 0xd1, 0x01, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x35, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x4b, 0x65, 0x79, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x12, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x53, 0x65, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x12, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x53, 0x65, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x42, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x35, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x4b, 0x65, 0x79, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x6f, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x22, 0x63, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x03, 0x62,
	0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x6f, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x03, 0x62, 0x6f, 0x74, 0x22, 0x66, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x8a, 0x01, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x03, 0x62, 0x6f, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x62, 0x6f, 0x74, 0x22, 0x49, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x35, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3c, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x6f, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x22, 0x0a, 0x04, 0x62, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x62, 0x6f, 0x74, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68,
	0x6f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x6f, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x33, 0x0a, 0x0b, 0x6e, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4e, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x6e, 0x6f, 0x52, 0x6f, 0x6c, 0x65,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x30, 0x0a, 0x0b, 0x62, 0x61, 0x64, 0x43, 0x68, 0x61, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61, 0x64,
	0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x62, 0x61, 0x64, 0x43,
	0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22,
	0xa8, 0x01, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x41, 0x64,
	0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69,
	0x73, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4c, 0x0a, 0x12, 0x41, 0x64,
	0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x53, 0x68, 0x6f, 0x70, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x58, 0x0a, 0x1c, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x42, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x4b, 0x65, 0x79, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x6f, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x42,
	0x79, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68,
	0x6f, 0x70, 0x49, 0x64, 0x32, 0xd6, 0x04, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x12, 0x34, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x12, 0x11, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f,
	0x70, 0x12, 0x0f, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x53, 0x68, 0x6f, 0x70, 0x12, 0x12, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x68, 0x6f,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x12, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x42, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c,
	0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x16, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0e,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x16,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x15, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x42, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x1d, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x42, 0x6f, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f,
	0x70, 0x49, 0x64, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x08, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x4b,
	0x65, 0x79, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x42, 0x79,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x33, 0x5a,
	0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6b, 0x68,
	0x6f, 0x76, 0x61, 0x73, 0x2f, 0x64, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Control_proto_rawDescOnce sync.Once
	file_Control_proto_rawDescData = file_Control_proto_rawDesc
)

func file_Control_proto_rawDescGZIP() []byte {
	file_Control_proto_rawDescOnce.Do(func() {
		file_Control_proto_rawDescData = protoimpl.X.CompressGZIP(file_Control_proto_rawDescData)
	})
	return file_Control_proto_rawDescData
}

var file_Control_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_Control_proto_goTypes = []interface{}{
	(*TelegramMessageInfo)(nil),          // 0: TelegramMessageInfo
	(*MessageInformation)(nil),           // 1: MessageInformation
	(*CommonBotInfo)(nil),                // 2: CommonBotInfo
	(*OptionalCommonBotInfo)(nil),        // 3: OptionalCommonBotInfo
	(*TelegramBotInfo)(nil),              // 4: TelegramBotInfo
	(*OptionalTelegramBotInfo)(nil),      // 5: OptionalTelegramBotInfo
	(*PlatformBotInfo)(nil),              // 6: PlatformBotInfo
	(*OptionalPlatformBotInfo)(nil),      // 7: OptionalPlatformBotInfo
	(*BotInfo)(nil),                      // 8: BotInfo
	(*OptionalBotInfo)(nil),              // 9: OptionalBotInfo
	(*CommonShopKey)(nil),                // 10: CommonShopKey
	(*TelegramStaffShopKey)(nil),         // 11: TelegramStaffShopKey
	(*ShopKey)(nil),                      // 12: ShopKey
	(*EmptyOkResponse)(nil),              // 13: EmptyOkResponse
	(*NoRoleResponse)(nil),               // 14: NoRoleResponse
	(*BadChatType)(nil),                  // 15: BadChatType
	(*DefaultResponse)(nil),              // 16: DefaultResponse
	(*AddQuestionAnswerRequest)(nil),     // 17: AddQuestionAnswerRequest
	(*ChangeBotStateRequest)(nil),        // 18: ChangeBotStateRequest
	(*AddShopRequest)(nil),               // 19: AddShopRequest
	(*DeleteShopRequest)(nil),            // 20: DeleteShopRequest
	(*ModifyShopRequest)(nil),            // 21: ModifyShopRequest
	(*ListShopsRequest)(nil),             // 22: ListShopsRequest
	(*ListBotSuccessResponse)(nil),       // 23: ListBotSuccessResponse
	(*ListShopsResponse)(nil),            // 24: ListShopsResponse
	(*ChangeUserRoleRequest)(nil),        // 25: ChangeUserRoleRequest
	(*AddQuestionRequest)(nil),           // 26: AddQuestionRequest
	(*NotifyBotStatusChangeRequest)(nil), // 27: NotifyBotStatusChangeRequest
	(*GetShopIdByKeyResponse)(nil),       // 28: GetShopIdByKeyResponse
}
var file_Control_proto_depIdxs = []int32{
	0,  // 0: MessageInformation.telegram:type_name -> TelegramMessageInfo
	4,  // 1: PlatformBotInfo.telegram:type_name -> TelegramBotInfo
	5,  // 2: OptionalPlatformBotInfo.telegram:type_name -> OptionalTelegramBotInfo
	2,  // 3: BotInfo.commonBotInfo:type_name -> CommonBotInfo
	6,  // 4: BotInfo.platformBotInfo:type_name -> PlatformBotInfo
	3,  // 5: OptionalBotInfo.commonBotInfo:type_name -> OptionalCommonBotInfo
	7,  // 6: OptionalBotInfo.platformBotInfo:type_name -> OptionalPlatformBotInfo
	10, // 7: ShopKey.common:type_name -> CommonShopKey
	11, // 8: ShopKey.telegramStaff:type_name -> TelegramStaffShopKey
	13, // 9: DefaultResponse.success:type_name -> EmptyOkResponse
	14, // 10: DefaultResponse.noRoleError:type_name -> NoRoleResponse
	15, // 11: DefaultResponse.badChatType:type_name -> BadChatType
	1,  // 12: AddQuestionAnswerRequest.messageInfo:type_name -> MessageInformation
	12, // 13: AddQuestionAnswerRequest.key:type_name -> ShopKey
	1,  // 14: ChangeBotStateRequest.messageInfo:type_name -> MessageInformation
	12, // 15: ChangeBotStateRequest.key:type_name -> ShopKey
	1,  // 16: AddShopRequest.messageInfo:type_name -> MessageInformation
	8,  // 17: AddShopRequest.bot:type_name -> BotInfo
	1,  // 18: DeleteShopRequest.messageInfo:type_name -> MessageInformation
	12, // 19: DeleteShopRequest.key:type_name -> ShopKey
	1,  // 20: ModifyShopRequest.messageInfo:type_name -> MessageInformation
	12, // 21: ModifyShopRequest.key:type_name -> ShopKey
	9,  // 22: ModifyShopRequest.bot:type_name -> OptionalBotInfo
	1,  // 23: ListShopsRequest.messageInfo:type_name -> MessageInformation
	2,  // 24: ListBotSuccessResponse.bots:type_name -> CommonBotInfo
	23, // 25: ListShopsResponse.success:type_name -> ListBotSuccessResponse
	14, // 26: ListShopsResponse.noRoleError:type_name -> NoRoleResponse
	15, // 27: ListShopsResponse.badChatType:type_name -> BadChatType
	1,  // 28: ChangeUserRoleRequest.messageInfo:type_name -> MessageInformation
	12, // 29: AddQuestionRequest.key:type_name -> ShopKey
	12, // 30: NotifyBotStatusChangeRequest.key:type_name -> ShopKey
	22, // 31: Control.ListShops:input_type -> ListShopsRequest
	19, // 32: Control.AddShop:input_type -> AddShopRequest
	21, // 33: Control.ModifyShop:input_type -> ModifyShopRequest
	20, // 34: Control.DeleteShop:input_type -> DeleteShopRequest
	17, // 35: Control.AddQuestionAnswer:input_type -> AddQuestionAnswerRequest
	26, // 36: Control.AddQuestion:input_type -> AddQuestionRequest
	18, // 37: Control.ChangeBotState:input_type -> ChangeBotStateRequest
	25, // 38: Control.ChangeUserRole:input_type -> ChangeUserRoleRequest
	27, // 39: Control.NotifyBotStatusChange:input_type -> NotifyBotStatusChangeRequest
	12, // 40: Control.GetShopIdByKey:input_type -> ShopKey
	24, // 41: Control.ListShops:output_type -> ListShopsResponse
	16, // 42: Control.AddShop:output_type -> DefaultResponse
	16, // 43: Control.ModifyShop:output_type -> DefaultResponse
	16, // 44: Control.DeleteShop:output_type -> DefaultResponse
	16, // 45: Control.AddQuestionAnswer:output_type -> DefaultResponse
	16, // 46: Control.AddQuestion:output_type -> DefaultResponse
	16, // 47: Control.ChangeBotState:output_type -> DefaultResponse
	16, // 48: Control.ChangeUserRole:output_type -> DefaultResponse
	16, // 49: Control.NotifyBotStatusChange:output_type -> DefaultResponse
	28, // 50: Control.GetShopIdByKey:output_type -> GetShopIdByKeyResponse
	41, // [41:51] is the sub-list for method output_type
	31, // [31:41] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_Control_proto_init() }
func file_Control_proto_init() {
	if File_Control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Control_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelegramMessageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonBotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalCommonBotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelegramBotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalTelegramBotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatformBotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalPlatformBotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalBotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonShopKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelegramStaffShopKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyOkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoRoleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BadChatType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddQuestionAnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeBotStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddShopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyShopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShopsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBotSuccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShopsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserRoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddQuestionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyBotStatusChangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Control_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopIdByKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Control_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_Control_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*MessageInformation_Telegram)(nil),
	}
	file_Control_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_Control_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_Control_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*PlatformBotInfo_Telegram)(nil),
	}
	file_Control_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*OptionalPlatformBotInfo_Telegram)(nil),
	}
	file_Control_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_Control_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*CommonShopKey_Id)(nil),
		(*CommonShopKey_Name)(nil),
		(*CommonShopKey_VkGroupId)(nil),
	}
	file_Control_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*TelegramStaffShopKey_GroupId)(nil),
	}
	file_Control_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ShopKey_Common)(nil),
		(*ShopKey_TelegramStaff)(nil),
	}
	file_Control_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*DefaultResponse_Success)(nil),
		(*DefaultResponse_NoRoleError)(nil),
		(*DefaultResponse_BadChatType)(nil),
	}
	file_Control_proto_msgTypes[24].OneofWrappers = []interface{}{
		(*ListShopsResponse_Success)(nil),
		(*ListShopsResponse_NoRoleError)(nil),
		(*ListShopsResponse_BadChatType)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Control_proto_goTypes,
		DependencyIndexes: file_Control_proto_depIdxs,
		MessageInfos:      file_Control_proto_msgTypes,
	}.Build()
	File_Control_proto = out.File
	file_Control_proto_rawDesc = nil
	file_Control_proto_goTypes = nil
	file_Control_proto_depIdxs = nil
}
