# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumer_actions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consumer_actions.proto',
  package='comsumer_actions',
  syntax='proto3',
  serialized_options=b'Z9github.com/nikhovas/diploma/go/lib/proto/comsumer_actions',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63onsumer_actions.proto\x12\x10\x63omsumer_actions\"r\n\x0b\x41\x63tionEvent\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\r\n\x05\x62otId\x18\x02 \x01(\t\x12\x0e\n\x06shopId\x18\x03 \x01(\x03\x12\x0c\n\x04time\x18\x04 \x01(\x04\x12\x13\n\x0bserviceName\x18\x05 \x01(\t\x12\x11\n\tneedOrder\x18\x06 \x01(\x08\"<\n\nNewMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x07replied\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\n\n\x08_replied\"D\n\x0fNewMessageBatch\x12\x31\n\x0bnewMessages\x18\x01 \x03(\x0b\x32\x1c.comsumer_actions.NewMessage\"\x08\n\x06Typing\"\xc2\x01\n\nUserAction\x12*\n\x06typing\x18\x01 \x01(\x0b\x32\x18.comsumer_actions.TypingH\x00\x12\x32\n\nnewMessage\x18\x02 \x01(\x0b\x32\x1c.comsumer_actions.NewMessageH\x00\x12<\n\x0fnewMessageBatch\x18\x03 \x01(\x0b\x32!.comsumer_actions.NewMessageBatchH\x00\x12\x0c\n\x04time\x18\x04 \x01(\x04\x42\x08\n\x06objectB;Z9github.com/nikhovas/diploma/go/lib/proto/comsumer_actionsb\x06proto3'
)




_ACTIONEVENT = _descriptor.Descriptor(
  name='ActionEvent',
  full_name='comsumer_actions.ActionEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='comsumer_actions.ActionEvent.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='botId', full_name='comsumer_actions.ActionEvent.botId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shopId', full_name='comsumer_actions.ActionEvent.shopId', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='comsumer_actions.ActionEvent.time', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serviceName', full_name='comsumer_actions.ActionEvent.serviceName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='needOrder', full_name='comsumer_actions.ActionEvent.needOrder', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=158,
)


_NEWMESSAGE = _descriptor.Descriptor(
  name='NewMessage',
  full_name='comsumer_actions.NewMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='comsumer_actions.NewMessage.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replied', full_name='comsumer_actions.NewMessage.replied', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_replied', full_name='comsumer_actions.NewMessage._replied',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=160,
  serialized_end=220,
)


_NEWMESSAGEBATCH = _descriptor.Descriptor(
  name='NewMessageBatch',
  full_name='comsumer_actions.NewMessageBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='newMessages', full_name='comsumer_actions.NewMessageBatch.newMessages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=290,
)


_TYPING = _descriptor.Descriptor(
  name='Typing',
  full_name='comsumer_actions.Typing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=300,
)


_USERACTION = _descriptor.Descriptor(
  name='UserAction',
  full_name='comsumer_actions.UserAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='typing', full_name='comsumer_actions.UserAction.typing', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='newMessage', full_name='comsumer_actions.UserAction.newMessage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='newMessageBatch', full_name='comsumer_actions.UserAction.newMessageBatch', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='comsumer_actions.UserAction.time', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='object', full_name='comsumer_actions.UserAction.object',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=303,
  serialized_end=497,
)

_NEWMESSAGE.oneofs_by_name['_replied'].fields.append(
  _NEWMESSAGE.fields_by_name['replied'])
_NEWMESSAGE.fields_by_name['replied'].containing_oneof = _NEWMESSAGE.oneofs_by_name['_replied']
_NEWMESSAGEBATCH.fields_by_name['newMessages'].message_type = _NEWMESSAGE
_USERACTION.fields_by_name['typing'].message_type = _TYPING
_USERACTION.fields_by_name['newMessage'].message_type = _NEWMESSAGE
_USERACTION.fields_by_name['newMessageBatch'].message_type = _NEWMESSAGEBATCH
_USERACTION.oneofs_by_name['object'].fields.append(
  _USERACTION.fields_by_name['typing'])
_USERACTION.fields_by_name['typing'].containing_oneof = _USERACTION.oneofs_by_name['object']
_USERACTION.oneofs_by_name['object'].fields.append(
  _USERACTION.fields_by_name['newMessage'])
_USERACTION.fields_by_name['newMessage'].containing_oneof = _USERACTION.oneofs_by_name['object']
_USERACTION.oneofs_by_name['object'].fields.append(
  _USERACTION.fields_by_name['newMessageBatch'])
_USERACTION.fields_by_name['newMessageBatch'].containing_oneof = _USERACTION.oneofs_by_name['object']
DESCRIPTOR.message_types_by_name['ActionEvent'] = _ACTIONEVENT
DESCRIPTOR.message_types_by_name['NewMessage'] = _NEWMESSAGE
DESCRIPTOR.message_types_by_name['NewMessageBatch'] = _NEWMESSAGEBATCH
DESCRIPTOR.message_types_by_name['Typing'] = _TYPING
DESCRIPTOR.message_types_by_name['UserAction'] = _USERACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActionEvent = _reflection.GeneratedProtocolMessageType('ActionEvent', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONEVENT,
  '__module__' : 'consumer_actions_pb2'
  # @@protoc_insertion_point(class_scope:comsumer_actions.ActionEvent)
  })
_sym_db.RegisterMessage(ActionEvent)

NewMessage = _reflection.GeneratedProtocolMessageType('NewMessage', (_message.Message,), {
  'DESCRIPTOR' : _NEWMESSAGE,
  '__module__' : 'consumer_actions_pb2'
  # @@protoc_insertion_point(class_scope:comsumer_actions.NewMessage)
  })
_sym_db.RegisterMessage(NewMessage)

NewMessageBatch = _reflection.GeneratedProtocolMessageType('NewMessageBatch', (_message.Message,), {
  'DESCRIPTOR' : _NEWMESSAGEBATCH,
  '__module__' : 'consumer_actions_pb2'
  # @@protoc_insertion_point(class_scope:comsumer_actions.NewMessageBatch)
  })
_sym_db.RegisterMessage(NewMessageBatch)

Typing = _reflection.GeneratedProtocolMessageType('Typing', (_message.Message,), {
  'DESCRIPTOR' : _TYPING,
  '__module__' : 'consumer_actions_pb2'
  # @@protoc_insertion_point(class_scope:comsumer_actions.Typing)
  })
_sym_db.RegisterMessage(Typing)

UserAction = _reflection.GeneratedProtocolMessageType('UserAction', (_message.Message,), {
  'DESCRIPTOR' : _USERACTION,
  '__module__' : 'consumer_actions_pb2'
  # @@protoc_insertion_point(class_scope:comsumer_actions.UserAction)
  })
_sym_db.RegisterMessage(UserAction)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
