# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumer_actions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63onsumer_actions.proto\x12\x10\x63omsumer_actions\"r\n\x0b\x41\x63tionEvent\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\r\n\x05\x62otId\x18\x02 \x01(\t\x12\x0e\n\x06shopId\x18\x03 \x01(\x03\x12\x0c\n\x04time\x18\x04 \x01(\x04\x12\x13\n\x0bserviceName\x18\x05 \x01(\t\x12\x11\n\tneedOrder\x18\x06 \x01(\x08\"H\n\nNewMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x07replied\x18\x02 \x01(\x03H\x00\x88\x01\x01\x12\n\n\x02id\x18\x03 \x01(\x04\x42\n\n\x08_replied\"D\n\x0fNewMessageBatch\x12\x31\n\x0bnewMessages\x18\x01 \x03(\x0b\x32\x1c.comsumer_actions.NewMessage\"\x08\n\x06Typing\"\xd0\x01\n\nUserAction\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12*\n\x06typing\x18\x02 \x01(\x0b\x32\x18.comsumer_actions.TypingH\x00\x12\x32\n\nnewMessage\x18\x03 \x01(\x0b\x32\x1c.comsumer_actions.NewMessageH\x00\x12<\n\x0fnewMessageBatch\x18\x04 \x01(\x0b\x32!.comsumer_actions.NewMessageBatchH\x00\x12\x0c\n\x04time\x18\x05 \x01(\x04\x42\x08\n\x06objectB;Z9github.com/nikhovas/diploma/go/lib/proto/comsumer_actionsb\x06proto3')



_ACTIONEVENT = DESCRIPTOR.message_types_by_name['ActionEvent']
_NEWMESSAGE = DESCRIPTOR.message_types_by_name['NewMessage']
_NEWMESSAGEBATCH = DESCRIPTOR.message_types_by_name['NewMessageBatch']
_TYPING = DESCRIPTOR.message_types_by_name['Typing']
_USERACTION = DESCRIPTOR.message_types_by_name['UserAction']
ActionEvent = _reflection.GeneratedProtocolMessageType('ActionEvent', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONEVENT,
  '__module__' : 'consumer_actions_pb2'
  # @@protoc_insertion_point(class_scope:comsumer_actions.ActionEvent)
  })
_sym_db.RegisterMessage(ActionEvent)

NewMessage = _reflection.GeneratedProtocolMessageType('NewMessage', (_message.Message,), {
  'DESCRIPTOR' : _NEWMESSAGE,
  '__module__' : 'consumer_actions_pb2'
  # @@protoc_insertion_point(class_scope:comsumer_actions.NewMessage)
  })
_sym_db.RegisterMessage(NewMessage)

NewMessageBatch = _reflection.GeneratedProtocolMessageType('NewMessageBatch', (_message.Message,), {
  'DESCRIPTOR' : _NEWMESSAGEBATCH,
  '__module__' : 'consumer_actions_pb2'
  # @@protoc_insertion_point(class_scope:comsumer_actions.NewMessageBatch)
  })
_sym_db.RegisterMessage(NewMessageBatch)

Typing = _reflection.GeneratedProtocolMessageType('Typing', (_message.Message,), {
  'DESCRIPTOR' : _TYPING,
  '__module__' : 'consumer_actions_pb2'
  # @@protoc_insertion_point(class_scope:comsumer_actions.Typing)
  })
_sym_db.RegisterMessage(Typing)

UserAction = _reflection.GeneratedProtocolMessageType('UserAction', (_message.Message,), {
  'DESCRIPTOR' : _USERACTION,
  '__module__' : 'consumer_actions_pb2'
  # @@protoc_insertion_point(class_scope:comsumer_actions.UserAction)
  })
_sym_db.RegisterMessage(UserAction)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z9github.com/nikhovas/diploma/go/lib/proto/comsumer_actions'
  _ACTIONEVENT._serialized_start=44
  _ACTIONEVENT._serialized_end=158
  _NEWMESSAGE._serialized_start=160
  _NEWMESSAGE._serialized_end=232
  _NEWMESSAGEBATCH._serialized_start=234
  _NEWMESSAGEBATCH._serialized_end=302
  _TYPING._serialized_start=304
  _TYPING._serialized_end=312
  _USERACTION._serialized_start=315
  _USERACTION._serialized_end=523
# @@protoc_insertion_point(module_scope)
