# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import control_grpc_client.Control_pb2 as Control__pb2


class ControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListShops = channel.unary_unary(
                '/Control/ListShops',
                request_serializer=Control__pb2.ListShopsRequest.SerializeToString,
                response_deserializer=Control__pb2.ListShopsResponse.FromString,
                )
        self.AddShop = channel.unary_unary(
                '/Control/AddShop',
                request_serializer=Control__pb2.AddShopRequest.SerializeToString,
                response_deserializer=Control__pb2.DefaultResponse.FromString,
                )
        self.ModifyShop = channel.unary_unary(
                '/Control/ModifyShop',
                request_serializer=Control__pb2.ModifyShopRequest.SerializeToString,
                response_deserializer=Control__pb2.DefaultResponse.FromString,
                )
        self.DeleteShop = channel.unary_unary(
                '/Control/DeleteShop',
                request_serializer=Control__pb2.DeleteShopRequest.SerializeToString,
                response_deserializer=Control__pb2.DefaultResponse.FromString,
                )
        self.AddQuestionAnswer = channel.unary_unary(
                '/Control/AddQuestionAnswer',
                request_serializer=Control__pb2.AddQuestionAnswerRequest.SerializeToString,
                response_deserializer=Control__pb2.DefaultResponse.FromString,
                )
        self.AddQuestion = channel.unary_unary(
                '/Control/AddQuestion',
                request_serializer=Control__pb2.AddQuestionRequest.SerializeToString,
                response_deserializer=Control__pb2.DefaultResponse.FromString,
                )
        self.ChangeBotState = channel.unary_unary(
                '/Control/ChangeBotState',
                request_serializer=Control__pb2.ChangeBotStateRequest.SerializeToString,
                response_deserializer=Control__pb2.DefaultResponse.FromString,
                )
        self.ChangeUserRole = channel.unary_unary(
                '/Control/ChangeUserRole',
                request_serializer=Control__pb2.ChangeUserRoleRequest.SerializeToString,
                response_deserializer=Control__pb2.DefaultResponse.FromString,
                )
        self.NotifyBotStatusChange = channel.unary_unary(
                '/Control/NotifyBotStatusChange',
                request_serializer=Control__pb2.NotifyBotStatusChangeRequest.SerializeToString,
                response_deserializer=Control__pb2.DefaultResponse.FromString,
                )


class ControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListShops(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddShop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyShop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteShop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddQuestionAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeBotState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeUserRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyBotStatusChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListShops': grpc.unary_unary_rpc_method_handler(
                    servicer.ListShops,
                    request_deserializer=Control__pb2.ListShopsRequest.FromString,
                    response_serializer=Control__pb2.ListShopsResponse.SerializeToString,
            ),
            'AddShop': grpc.unary_unary_rpc_method_handler(
                    servicer.AddShop,
                    request_deserializer=Control__pb2.AddShopRequest.FromString,
                    response_serializer=Control__pb2.DefaultResponse.SerializeToString,
            ),
            'ModifyShop': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyShop,
                    request_deserializer=Control__pb2.ModifyShopRequest.FromString,
                    response_serializer=Control__pb2.DefaultResponse.SerializeToString,
            ),
            'DeleteShop': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteShop,
                    request_deserializer=Control__pb2.DeleteShopRequest.FromString,
                    response_serializer=Control__pb2.DefaultResponse.SerializeToString,
            ),
            'AddQuestionAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddQuestionAnswer,
                    request_deserializer=Control__pb2.AddQuestionAnswerRequest.FromString,
                    response_serializer=Control__pb2.DefaultResponse.SerializeToString,
            ),
            'AddQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AddQuestion,
                    request_deserializer=Control__pb2.AddQuestionRequest.FromString,
                    response_serializer=Control__pb2.DefaultResponse.SerializeToString,
            ),
            'ChangeBotState': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeBotState,
                    request_deserializer=Control__pb2.ChangeBotStateRequest.FromString,
                    response_serializer=Control__pb2.DefaultResponse.SerializeToString,
            ),
            'ChangeUserRole': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeUserRole,
                    request_deserializer=Control__pb2.ChangeUserRoleRequest.FromString,
                    response_serializer=Control__pb2.DefaultResponse.SerializeToString,
            ),
            'NotifyBotStatusChange': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyBotStatusChange,
                    request_deserializer=Control__pb2.NotifyBotStatusChangeRequest.FromString,
                    response_serializer=Control__pb2.DefaultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Control(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListShops(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/ListShops',
            Control__pb2.ListShopsRequest.SerializeToString,
            Control__pb2.ListShopsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddShop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/AddShop',
            Control__pb2.AddShopRequest.SerializeToString,
            Control__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyShop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/ModifyShop',
            Control__pb2.ModifyShopRequest.SerializeToString,
            Control__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteShop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/DeleteShop',
            Control__pb2.DeleteShopRequest.SerializeToString,
            Control__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddQuestionAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/AddQuestionAnswer',
            Control__pb2.AddQuestionAnswerRequest.SerializeToString,
            Control__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/AddQuestion',
            Control__pb2.AddQuestionRequest.SerializeToString,
            Control__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeBotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/ChangeBotState',
            Control__pb2.ChangeBotStateRequest.SerializeToString,
            Control__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeUserRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/ChangeUserRole',
            Control__pb2.ChangeUserRoleRequest.SerializeToString,
            Control__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyBotStatusChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/NotifyBotStatusChange',
            Control__pb2.NotifyBotStatusChangeRequest.SerializeToString,
            Control__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
