# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumer_bot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.common import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='consumer_bot.proto',
  package='consumer_bot',
  syntax='proto3',
  serialized_options=b'Z5github.com/nikhovas/diploma/go/lib/proto/consumer_bot',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63onsumer_bot.proto\x12\x0c\x63onsumer_bot\x1a\x0c\x63ommon.proto\"R\n\x18SimpleMessageInformation\x12(\n\x0bmsgLocation\x18\x01 \x01(\x0b\x32\x13.common.MsgLocation\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x87\x01\n\x17ReplyMessageInformation\x12(\n\x0bmsgLocation\x18\x01 \x01(\x0b\x32\x13.common.MsgLocation\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x16\n\x0ereplyMessageId\x18\x03 \x01(\x04\x12\x1c\n\x14replyUnsupportedText\x18\x04 \x01(\t2\xb4\x01\n\x08VkServer\x12T\n\x11SendSimpleMessage\x12&.consumer_bot.SimpleMessageInformation\x1a\x15.common.EmptyResponse\"\x00\x12R\n\x10SendReplyMessage\x12%.consumer_bot.ReplyMessageInformation\x1a\x15.common.EmptyResponse\"\x00\x42\x37Z5github.com/nikhovas/diploma/go/lib/proto/consumer_botb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_SIMPLEMESSAGEINFORMATION = _descriptor.Descriptor(
  name='SimpleMessageInformation',
  full_name='consumer_bot.SimpleMessageInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgLocation', full_name='consumer_bot.SimpleMessageInformation.msgLocation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='consumer_bot.SimpleMessageInformation.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=132,
)


_REPLYMESSAGEINFORMATION = _descriptor.Descriptor(
  name='ReplyMessageInformation',
  full_name='consumer_bot.ReplyMessageInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgLocation', full_name='consumer_bot.ReplyMessageInformation.msgLocation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='consumer_bot.ReplyMessageInformation.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replyMessageId', full_name='consumer_bot.ReplyMessageInformation.replyMessageId', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replyUnsupportedText', full_name='consumer_bot.ReplyMessageInformation.replyUnsupportedText', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=270,
)

_SIMPLEMESSAGEINFORMATION.fields_by_name['msgLocation'].message_type = common__pb2._MSGLOCATION
_REPLYMESSAGEINFORMATION.fields_by_name['msgLocation'].message_type = common__pb2._MSGLOCATION
DESCRIPTOR.message_types_by_name['SimpleMessageInformation'] = _SIMPLEMESSAGEINFORMATION
DESCRIPTOR.message_types_by_name['ReplyMessageInformation'] = _REPLYMESSAGEINFORMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleMessageInformation = _reflection.GeneratedProtocolMessageType('SimpleMessageInformation', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEMESSAGEINFORMATION,
  '__module__' : 'consumer_bot_pb2'
  # @@protoc_insertion_point(class_scope:consumer_bot.SimpleMessageInformation)
  })
_sym_db.RegisterMessage(SimpleMessageInformation)

ReplyMessageInformation = _reflection.GeneratedProtocolMessageType('ReplyMessageInformation', (_message.Message,), {
  'DESCRIPTOR' : _REPLYMESSAGEINFORMATION,
  '__module__' : 'consumer_bot_pb2'
  # @@protoc_insertion_point(class_scope:consumer_bot.ReplyMessageInformation)
  })
_sym_db.RegisterMessage(ReplyMessageInformation)


DESCRIPTOR._options = None

_VKSERVER = _descriptor.ServiceDescriptor(
  name='VkServer',
  full_name='consumer_bot.VkServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=273,
  serialized_end=453,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendSimpleMessage',
    full_name='consumer_bot.VkServer.SendSimpleMessage',
    index=0,
    containing_service=None,
    input_type=_SIMPLEMESSAGEINFORMATION,
    output_type=common__pb2._EMPTYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendReplyMessage',
    full_name='consumer_bot.VkServer.SendReplyMessage',
    index=1,
    containing_service=None,
    input_type=_REPLYMESSAGEINFORMATION,
    output_type=common__pb2._EMPTYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VKSERVER)

DESCRIPTOR.services_by_name['VkServer'] = _VKSERVER

# @@protoc_insertion_point(module_scope)
