# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from servers.QuestionWorker import QuestionWorker_pb2 as servers_dot_QuestionWorker_dot_QuestionWorker__pb2


class VkServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQuestionAnswer = channel.unary_unary(
                '/VkServer/GetQuestionAnswer',
                request_serializer=servers_dot_QuestionWorker_dot_QuestionWorker__pb2.GetQuestionAnswerRequest.SerializeToString,
                response_deserializer=servers_dot_QuestionWorker_dot_QuestionWorker__pb2.GetQuestionAnswerResponse.FromString,
                )
        self.AddQuestion = channel.unary_unary(
                '/VkServer/AddQuestion',
                request_serializer=servers_dot_QuestionWorker_dot_QuestionWorker__pb2.AddQuestionRequest.SerializeToString,
                response_deserializer=servers_dot_QuestionWorker_dot_QuestionWorker__pb2.AddQuestionResponse.FromString,
                )


class VkServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetQuestionAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VkServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQuestionAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuestionAnswer,
                    request_deserializer=servers_dot_QuestionWorker_dot_QuestionWorker__pb2.GetQuestionAnswerRequest.FromString,
                    response_serializer=servers_dot_QuestionWorker_dot_QuestionWorker__pb2.GetQuestionAnswerResponse.SerializeToString,
            ),
            'AddQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AddQuestion,
                    request_deserializer=servers_dot_QuestionWorker_dot_QuestionWorker__pb2.AddQuestionRequest.FromString,
                    response_serializer=servers_dot_QuestionWorker_dot_QuestionWorker__pb2.AddQuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VkServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VkServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetQuestionAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/VkServer/GetQuestionAnswer',
            servers_dot_QuestionWorker_dot_QuestionWorker__pb2.GetQuestionAnswerRequest.SerializeToString,
            servers_dot_QuestionWorker_dot_QuestionWorker__pb2.GetQuestionAnswerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/VkServer/AddQuestion',
            servers_dot_QuestionWorker_dot_QuestionWorker__pb2.AddQuestionRequest.SerializeToString,
            servers_dot_QuestionWorker_dot_QuestionWorker__pb2.AddQuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
