# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servers/QuestionWorker/QuestionWorker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='servers/QuestionWorker/QuestionWorker.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z2github.com/nikhovas/diploma/proto/servers/VkServer',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+servers/QuestionWorker/QuestionWorker.proto\"G\n\x18GetQuestionAnswerRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x19\n\x11previousQuestions\x18\x02 \x03(\t\"R\n\x19GetQuestionAnswerResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x10\n\x08repeated\x18\x02 \x01(\x08\x12\x13\n\x0bprobability\x18\x03 \x01(\x02\"6\n\x12\x41\x64\x64QuestionRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\"\x15\n\x13\x41\x64\x64QuestionResponse2\x94\x01\n\x08VkServer\x12L\n\x11GetQuestionAnswer\x12\x19.GetQuestionAnswerRequest\x1a\x1a.GetQuestionAnswerResponse\"\x00\x12:\n\x0b\x41\x64\x64Question\x12\x13.AddQuestionRequest\x1a\x14.AddQuestionResponse\"\x00\x42\x34Z2github.com/nikhovas/diploma/proto/servers/VkServerb\x06proto3'
)




_GETQUESTIONANSWERREQUEST = _descriptor.Descriptor(
  name='GetQuestionAnswerRequest',
  full_name='GetQuestionAnswerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='GetQuestionAnswerRequest.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previousQuestions', full_name='GetQuestionAnswerRequest.previousQuestions', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=118,
)


_GETQUESTIONANSWERRESPONSE = _descriptor.Descriptor(
  name='GetQuestionAnswerResponse',
  full_name='GetQuestionAnswerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='GetQuestionAnswerResponse.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repeated', full_name='GetQuestionAnswerResponse.repeated', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='probability', full_name='GetQuestionAnswerResponse.probability', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=202,
)


_ADDQUESTIONREQUEST = _descriptor.Descriptor(
  name='AddQuestionRequest',
  full_name='AddQuestionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='AddQuestionRequest.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='answer', full_name='AddQuestionRequest.answer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=258,
)


_ADDQUESTIONRESPONSE = _descriptor.Descriptor(
  name='AddQuestionResponse',
  full_name='AddQuestionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=281,
)

DESCRIPTOR.message_types_by_name['GetQuestionAnswerRequest'] = _GETQUESTIONANSWERREQUEST
DESCRIPTOR.message_types_by_name['GetQuestionAnswerResponse'] = _GETQUESTIONANSWERRESPONSE
DESCRIPTOR.message_types_by_name['AddQuestionRequest'] = _ADDQUESTIONREQUEST
DESCRIPTOR.message_types_by_name['AddQuestionResponse'] = _ADDQUESTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetQuestionAnswerRequest = _reflection.GeneratedProtocolMessageType('GetQuestionAnswerRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETQUESTIONANSWERREQUEST,
  '__module__' : 'servers.QuestionWorker.QuestionWorker_pb2'
  # @@protoc_insertion_point(class_scope:GetQuestionAnswerRequest)
  })
_sym_db.RegisterMessage(GetQuestionAnswerRequest)

GetQuestionAnswerResponse = _reflection.GeneratedProtocolMessageType('GetQuestionAnswerResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETQUESTIONANSWERRESPONSE,
  '__module__' : 'servers.QuestionWorker.QuestionWorker_pb2'
  # @@protoc_insertion_point(class_scope:GetQuestionAnswerResponse)
  })
_sym_db.RegisterMessage(GetQuestionAnswerResponse)

AddQuestionRequest = _reflection.GeneratedProtocolMessageType('AddQuestionRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDQUESTIONREQUEST,
  '__module__' : 'servers.QuestionWorker.QuestionWorker_pb2'
  # @@protoc_insertion_point(class_scope:AddQuestionRequest)
  })
_sym_db.RegisterMessage(AddQuestionRequest)

AddQuestionResponse = _reflection.GeneratedProtocolMessageType('AddQuestionResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDQUESTIONRESPONSE,
  '__module__' : 'servers.QuestionWorker.QuestionWorker_pb2'
  # @@protoc_insertion_point(class_scope:AddQuestionResponse)
  })
_sym_db.RegisterMessage(AddQuestionResponse)


DESCRIPTOR._options = None

_VKSERVER = _descriptor.ServiceDescriptor(
  name='VkServer',
  full_name='VkServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=284,
  serialized_end=432,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetQuestionAnswer',
    full_name='VkServer.GetQuestionAnswer',
    index=0,
    containing_service=None,
    input_type=_GETQUESTIONANSWERREQUEST,
    output_type=_GETQUESTIONANSWERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddQuestion',
    full_name='VkServer.AddQuestion',
    index=1,
    containing_service=None,
    input_type=_ADDQUESTIONREQUEST,
    output_type=_ADDQUESTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VKSERVER)

DESCRIPTOR.services_by_name['VkServer'] = _VKSERVER

# @@protoc_insertion_point(module_scope)
